websites:
  - name: webserver1
    src:  /home/yasin/lab4/webpage1/index.html
    dest: /var/www/html/index.html
  - name: webserver2
    src:  /home/yasin/lab4/webpage2/index.html
    dest: /var/www/html/index.html