apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyprometheus-deployment
  labels:
    app: pyprometheus
spec:
  replicas: 2  # Running one pod on each worker node
  selector:
    matchLabels:
      app: pyprometheus
  template:
    metadata:
      labels:
        app: pyprometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8181"
        prometheus.io/path: "/metrics"
    spec:
      nodeSelector:
        role: worker-node
      containers:
      - name: pyprometheus
        image: konami98/py_keda:v1
        ports:
        - containerPort: 8181
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"