apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pyprometheus-scaledobject
spec:
  scaleTargetRef:
    name: pyprometheus-deployment
  minReplicaCount: 2
  maxReplicaCount: 6
  cooldownPeriod: 10
  pollingInterval: 5
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
          policies:
          - type: Pods
            value: 1
            periodSeconds: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.prometheus.svc.cluster.local:80
      metricName: request_count
      threshold: '100'  # Scale when total requests exceed 100 in last 30s
      query: |
        sum(increase(http_requests_total[30s])) or vector(0)