apiVersion: v1
kind: Service
metadata:
  name: pyprometheus-service
spec:
  type: NodePort
  selector:
    app: pyprometheus
  ports:
    - port: 8181
      targetPort: 8181
      nodePort: 30081
      protocol: TCP