apiVersion: v1 
kind: Pod 
metadata:
  name: my-db
  labels:
    name: my-db
spec:
  containers:
  - name: my-db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: MYSQL_ROOT_PASSWORD
    
    - name: MYSQL_USER
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: MYSQL_USER

    - name: MYSQL_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: MYSQL_PASSWORD
