apiVersion: v1
kind: Pod
metadata:
  name: busybox
  annotations:
    container.apparmor.security.beta.kubernetes.io/busybox: unconfined
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: ["sleep", "3600"]