apiVersion: v1
kind: Pod
metadata:
  name: my-db
spec:
  containers:
  - name: mysql
    image: mysql
    envFrom:
    - configMapRef:
        name: db-config
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: db-config
