---
- name: Create VPC, subnet, route table, internet gateway and launch EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vpc_cidr_block: "10.0.0.0/16"
    subnet_cidr_block: "10.0.1.0/24"
    region: "ap-southeast-1"  # Replace with the your preferred region
    ami: "ami-060e277c0d4cce553" # Replace with your preferred AMI ID
    instance_type: "t2.micro"
    key_name: "my-key-pair"
    security_group_name: "my_security_group"
    security_group_description: "My security group for EC2 instance"
    private_key_path: "/root/.ssh/id_rsa" # Replace with your key path

  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: my_vpc
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ region }}"
        tags:
          Name: my_vpc
      register: vpc

    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr_block }}"
        region: "{{ region }}"
        tags:
          Name: my_subnet
      register: subnet

    - name: Create internet gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: my_igw
      register: igw

    - name: Set up public subnet route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: Public-route-table
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: public_route_table

    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_description }}"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        tags:
          Name: "{{ security_group_name }}"
      register: sg

    - name: Create key pair using key_material obtained using 'file' lookup plugin
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        key_material: "{{ lookup('file', private_key_path + '.pub') }}"
      register: key_pair

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: my_instance
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        security_group: "{{ sg.group_id }}"
        network:
          assign_public_ip: true
        wait: yes
        tags:
          Name: my_instance
      register: ec2_instance
      
    - name: Output instance information
      debug:
        msg: "EC2 instance launched with ID: {{ ec2_instance.instance_ids[0] }} and Public IP: {{ ec2_instance.instances[0].public_ip_address }}"